/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package tests-0.0.1 */
#ifndef VERSION_tests
#define VERSION_tests "0.0.1"
#endif /* VERSION_tests */
#ifndef MIN_VERSION_tests
#define MIN_VERSION_tests(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_tests */

/* package HTTP-4000.3.16 */
#ifndef VERSION_HTTP
#define VERSION_HTTP "4000.3.16"
#endif /* VERSION_HTTP */
#ifndef MIN_VERSION_HTTP
#define MIN_VERSION_HTTP(major1,major2,minor) (\
  (major1) <  4000 || \
  (major1) == 4000 && (major2) <  3 || \
  (major1) == 4000 && (major2) == 3 && (minor) <= 16)
#endif /* MIN_VERSION_HTTP */

/* package JuicyPixels-3.3.5 */
#ifndef VERSION_JuicyPixels
#define VERSION_JuicyPixels "3.3.5"
#endif /* VERSION_JuicyPixels */
#ifndef MIN_VERSION_JuicyPixels
#define MIN_VERSION_JuicyPixels(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  3 || \
  (major1) == 3 && (major2) == 3 && (minor) <= 5)
#endif /* MIN_VERSION_JuicyPixels */

/* package QuickCheck-2.14.2 */
#ifndef VERSION_QuickCheck
#define VERSION_QuickCheck "2.14.2"
#endif /* VERSION_QuickCheck */
#ifndef MIN_VERSION_QuickCheck
#define MIN_VERSION_QuickCheck(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  14 || \
  (major1) == 2 && (major2) == 14 && (minor) <= 2)
#endif /* MIN_VERSION_QuickCheck */

/* package array-0.5.4.0 */
#ifndef VERSION_array
#define VERSION_array "0.5.4.0"
#endif /* VERSION_array */
#ifndef MIN_VERSION_array
#define MIN_VERSION_array(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_array */

/* package base-4.14.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 1)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package containers-0.6.2.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.2.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 2)
#endif /* MIN_VERSION_containers */

/* package generic-random-1.3.0.1 */
#ifndef VERSION_generic_random
#define VERSION_generic_random "1.3.0.1"
#endif /* VERSION_generic_random */
#ifndef MIN_VERSION_generic_random
#define MIN_VERSION_generic_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_generic_random */

/* package hspec-2.7.8 */
#ifndef VERSION_hspec
#define VERSION_hspec "2.7.8"
#endif /* VERSION_hspec */
#ifndef MIN_VERSION_hspec
#define MIN_VERSION_hspec(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  7 || \
  (major1) == 2 && (major2) == 7 && (minor) <= 8)
#endif /* MIN_VERSION_hspec */

/* package http-types-0.12.3 */
#ifndef VERSION_http_types
#define VERSION_http_types "0.12.3"
#endif /* VERSION_http_types */
#ifndef MIN_VERSION_http_types
#define MIN_VERSION_http_types(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 3)
#endif /* MIN_VERSION_http_types */

/* package parallel-3.2.2.0 */
#ifndef VERSION_parallel
#define VERSION_parallel "3.2.2.0"
#endif /* VERSION_parallel */
#ifndef MIN_VERSION_parallel
#define MIN_VERSION_parallel(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_parallel */

/* package sqlite-simple-0.4.18.0 */
#ifndef VERSION_sqlite_simple
#define VERSION_sqlite_simple "0.4.18.0"
#endif /* VERSION_sqlite_simple */
#ifndef MIN_VERSION_sqlite_simple
#define MIN_VERSION_sqlite_simple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 18)
#endif /* MIN_VERSION_sqlite_simple */

/* package template-haskell-2.16.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.16.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  16 || \
  (major1) == 2 && (major2) == 16 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */

/* package text-1.2.4.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.4.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_text */

/* package transformers-0.5.6.2 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.6.2"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_transformers */

/* package wai-3.2.3 */
#ifndef VERSION_wai
#define VERSION_wai "3.2.3"
#endif /* VERSION_wai */
#ifndef MIN_VERSION_wai
#define MIN_VERSION_wai(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_wai */

/* package warp-3.3.14 */
#ifndef VERSION_warp
#define VERSION_warp "3.3.14"
#endif /* VERSION_warp */
#ifndef MIN_VERSION_warp
#define MIN_VERSION_warp(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  3 || \
  (major1) == 3 && (major2) == 3 && (minor) <= 14)
#endif /* MIN_VERSION_warp */

/* tool gcc-12.0.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "12.0.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  12 || \
  (major1) == 12 && (major2) <  0 || \
  (major1) == 12 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.4 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.4"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.4 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.4"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.10.4 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.4"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "tests-0.0.1-JRb9yUnZ890KQ4TAbLEJlJ"
#endif /* CURRENT_PACKAGE_KEY */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "tests-0.0.1-JRb9yUnZ890KQ4TAbLEJlJ"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.0.1"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
